language: php
php:
  - '5.6'
  - '7.0'

before_install: phpenv config-add travis-composer-php.ini

before_script:
  - composer install --no-interaction
  - touch storage/database.sqlite
  - php artisan migrate

script:
  - vendor/bin/phpunit